# Linux executables
# executables:
#   chrome:
#     command:
#       - /usr/bin/google-chrome-stable
#       - --new-tab
#   firefox:
#     command:
#       - /usr/bin/firefox
#       - --new-tab
#       - --url

# macOS executables
executables:
  chrome:
    command:
      - open
      - -a
      - Google Chrome
  firefox:
    command:
      - open
      - -a
      - Firefox

shortcuts:
  any:
    template: "%s"
  blank:
    template: "about:blank"
  google:
    template: https://www.google.com/search?q=%s